import 'package:flutter/cupertino.dart';
import 'package:islami_app/presentation/screens/main_layout/tabs/quran_screen/quran_screen.dart';
import 'package:islami_app/presentation/screens/main_layout/tabs/quran_screen/widgets/most_recently_card.dart';

class SurahDataModel {
  String suraNameAr;
  String suraNameEg;
  String ayaNumber;
  int index;

  // Constructor to initialize the attributes
  SurahDataModel({
    required this.suraNameAr,
    required this.suraNameEg,
    required this.ayaNumber,
    required this.index,
  });
}



List<SurahDataModel> surahList = [
  SurahDataModel(index: 1, suraNameAr: "الفاتحه", suraNameEg: "Al-Fatiha", ayaNumber: "7"),
  SurahDataModel(index: 2, suraNameAr: "البقرة", suraNameEg: "Al-Baqarah", ayaNumber: "286"),
  SurahDataModel(index: 3, suraNameAr: "آل عمران", suraNameEg: "Aal-E-Imran", ayaNumber: "200"),
  SurahDataModel(index: 4, suraNameAr: "النساء", suraNameEg: "An-Nisa'", ayaNumber: "176"),
  SurahDataModel(index: 5, suraNameAr: "المائدة", suraNameEg: "Al-Ma'idah", ayaNumber: "120"),
  SurahDataModel(index: 6, suraNameAr: "الأنعام", suraNameEg: "Al-An'am", ayaNumber: "165"),
  SurahDataModel(index: 7, suraNameAr: "الأعراف", suraNameEg: "Al-A'raf", ayaNumber: "206"),
  SurahDataModel(index: 8, suraNameAr: "الأنفال", suraNameEg: "Al-Anfal", ayaNumber: "75"),
  SurahDataModel(index: 9, suraNameAr: "التوبة", suraNameEg: "At-Tawbah", ayaNumber: "129"),
  SurahDataModel(index: 10, suraNameAr: "يونس", suraNameEg: "Yunus", ayaNumber: "109"),
  SurahDataModel(index: 11, suraNameAr: "هود", suraNameEg: "Hud", ayaNumber: "123"),
  SurahDataModel(index: 12, suraNameAr: "يوسف", suraNameEg: "Yusuf", ayaNumber: "111"),
  SurahDataModel(index: 13, suraNameAr: "الرعد", suraNameEg: "Ar-Ra'd", ayaNumber: "43"),
  SurahDataModel(index: 14, suraNameAr: "إبراهيم", suraNameEg: "Ibrahim", ayaNumber: "52"),
  SurahDataModel(index: 15, suraNameAr: "الحجر", suraNameEg: "Al-Hijr", ayaNumber: "99"),
  SurahDataModel(index: 16, suraNameAr: "النحل", suraNameEg: "An-Nahl", ayaNumber: "128"),
  SurahDataModel(index: 17, suraNameAr: "الإسراء", suraNameEg: "Al-Isra", ayaNumber: "111"),
  SurahDataModel(index: 18, suraNameAr: "الكهف", suraNameEg: "Al-Kahf", ayaNumber: "110"),
  SurahDataModel(index: 19, suraNameAr: "مريم", suraNameEg: "Maryam", ayaNumber: "98"),
  SurahDataModel(index: 20, suraNameAr: "طه", suraNameEg: "Ta-Ha", ayaNumber: "135"),
  SurahDataModel(index: 21, suraNameAr: "الأنبياء", suraNameEg: "Al-Anbiya", ayaNumber: "112"),
  SurahDataModel(index: 22, suraNameAr: "الحج", suraNameEg: "Al-Hajj", ayaNumber: "78"),
  SurahDataModel(index: 23, suraNameAr: "المؤمنون", suraNameEg: "Al-Mu'minun", ayaNumber: "118"),
  SurahDataModel(index: 24, suraNameAr: "النّور", suraNameEg: "An-Nur", ayaNumber: "64"),
  SurahDataModel(index: 25, suraNameAr: "الفرقان", suraNameEg: "Al-Furqan", ayaNumber: "77"),
  SurahDataModel(index: 26, suraNameAr: "الشعراء", suraNameEg: "Ash-Shu'ara", ayaNumber: "227"),
  SurahDataModel(index: 27, suraNameAr: "النّمل", suraNameEg: "An-Naml", ayaNumber: "93"),
  SurahDataModel(index: 28, suraNameAr: "القصص", suraNameEg: "Al-Qasas", ayaNumber: "88"),
  SurahDataModel(index: 29, suraNameAr: "العنكبوت", suraNameEg: "Al-Ankabut", ayaNumber: "69"),
  SurahDataModel(index: 30, suraNameAr: "الرّوم", suraNameEg: "Ar-Rum", ayaNumber: "60"),
  SurahDataModel(index: 31, suraNameAr: "لقمان", suraNameEg: "Luqman", ayaNumber: "34"),
  SurahDataModel(index: 32, suraNameAr: "السجدة", suraNameEg: "As-Sajda", ayaNumber: "30"),
  SurahDataModel(index: 33, suraNameAr: "الأحزاب", suraNameEg: "Al-Ahzab", ayaNumber: "73"),
  SurahDataModel(index: 34, suraNameAr: "سبأ", suraNameEg: "Saba", ayaNumber: "54"),
  SurahDataModel(index: 35, suraNameAr: "فاطر", suraNameEg: "Fatir", ayaNumber: "45"),
  SurahDataModel(index: 36, suraNameAr: "يس", suraNameEg: "Ya-Sin", ayaNumber: "83"),
  SurahDataModel(index: 37, suraNameAr: "الصافات", suraNameEg: "As-Saffat", ayaNumber: "182"),
  SurahDataModel(index: 38, suraNameAr: "ص", suraNameEg: "Sad", ayaNumber: "88"),
  SurahDataModel(index: 39, suraNameAr: "الزمر", suraNameEg: "Az-Zumar", ayaNumber: "75"),
  SurahDataModel(index: 40, suraNameAr: "غافر", suraNameEg: "Ghafir", ayaNumber: "85"),
  SurahDataModel(index: 41, suraNameAr: "فصّلت", suraNameEg: "Fussilat", ayaNumber: "46"),
  SurahDataModel(index: 42, suraNameAr: "الشورى", suraNameEg: "Ash-Shura", ayaNumber: "53"),
  SurahDataModel(index: 43, suraNameAr: "الزخرف", suraNameEg: "Az-Zukhruf", ayaNumber: "89"),
  SurahDataModel(index: 44, suraNameAr: "الدّخان", suraNameEg: "Ad-Dukhan", ayaNumber: "59"),
  SurahDataModel(index: 45, suraNameAr: "الجاثية", suraNameEg: "Al-Jathiya", ayaNumber: "37"),
  SurahDataModel(index: 46, suraNameAr: "الأحقاف", suraNameEg: "Al-Ahqaf", ayaNumber: "35"),
  SurahDataModel(index: 47, suraNameAr: "محمد", suraNameEg: "Muhammad", ayaNumber: "38"),
  SurahDataModel(index: 48, suraNameAr: "الفتح", suraNameEg: "Al-Fath", ayaNumber: "29"),
  SurahDataModel(index: 49, suraNameAr: "الحجرات", suraNameEg: "Al-Hujurat", ayaNumber: "18"),
  SurahDataModel(index: 50, suraNameAr: "ق", suraNameEg: "Qaf", ayaNumber: "45"),
  SurahDataModel(index: 51, suraNameAr: "الذاريات", suraNameEg: "Adh-Dhariyat", ayaNumber: "60"),
  SurahDataModel(index: 52, suraNameAr: "الطور", suraNameEg: "At-Tur", ayaNumber: "49"),
  SurahDataModel(index: 53, suraNameAr: "النجم", suraNameEg: "An-Najm", ayaNumber: "62"),
  SurahDataModel(index: 54, suraNameAr: "القمر", suraNameEg: "Al-Qamar", ayaNumber: "55"),
  SurahDataModel(index: 55, suraNameAr: "الرحمن", suraNameEg: "Ar-Rahman", ayaNumber: "78"),
  SurahDataModel(index: 56, suraNameAr: "الواقعة", suraNameEg: "Al-Waqi'a", ayaNumber: "96"),
  SurahDataModel(index: 57, suraNameAr: "الحديد", suraNameEg: "Al-Hadid", ayaNumber: "29"),
  SurahDataModel(index: 58, suraNameAr: "المجادلة", suraNameEg: "Al-Mujadila", ayaNumber: "22"),
  SurahDataModel(index: 59, suraNameAr: "الحشر", suraNameEg: "Al-Hashr", ayaNumber: "24"),
  SurahDataModel(index: 60, suraNameAr: "الممتحنة", suraNameEg: "Al-Mumtahina", ayaNumber: "13"),
  SurahDataModel(index: 61, suraNameAr: "الصف", suraNameEg: "As-Saff", ayaNumber: "14"),
  SurahDataModel(index: 62, suraNameAr: "الجمعة", suraNameEg: "Al-Jumu'a", ayaNumber: "11"),
  SurahDataModel(index: 63, suraNameAr: "المنافقون", suraNameEg: "Al-Munafiqun", ayaNumber: "11"),
  SurahDataModel(index: 64, suraNameAr: "التغابن", suraNameEg: "At-Taghabun", ayaNumber: "18"),
  SurahDataModel(index: 65, suraNameAr: "الطلاق", suraNameEg: "At-Talaq", ayaNumber: "12"),
  SurahDataModel(index: 66, suraNameAr: "التحريم", suraNameEg: "At-Tahrim", ayaNumber: "12"),
  SurahDataModel(index: 67, suraNameAr: "الملك", suraNameEg: "Al-Mulk", ayaNumber: "30"),
  SurahDataModel(index: 68, suraNameAr: "القلم", suraNameEg: "Al-Qalam", ayaNumber: "52"),
  SurahDataModel(index: 69, suraNameAr: "الحاقة", suraNameEg: "Al-Haqqah", ayaNumber: "58"),
  SurahDataModel(index: 70, suraNameAr: "المعارج", suraNameEg: "Al-Ma'arij", ayaNumber: "44"),
  SurahDataModel(index: 71, suraNameAr: "نوح", suraNameEg: "Nuh", ayaNumber: "28"),
  SurahDataModel(index: 72, suraNameAr: "الجن", suraNameEg: "Al-Jinn", ayaNumber: "72"),
  SurahDataModel(index: 73, suraNameAr: "المزّمّل", suraNameEg: "Al-Muzzammil", ayaNumber: "20"),
  SurahDataModel(index: 74, suraNameAr: "المدّثر", suraNameEg: "Al-Muddathir", ayaNumber: "56"),
  SurahDataModel(index: 75, suraNameAr: "القيامة", suraNameEg: "Al-Qiyama", ayaNumber: "40"),
  SurahDataModel(index: 76, suraNameAr: "الإنسان", suraNameEg: "Al-Insan", ayaNumber: "31"),
  SurahDataModel(index: 77, suraNameAr: "المرسلات", suraNameEg: "Al-Mursalat", ayaNumber: "50"),
  SurahDataModel(index: 78, suraNameAr: "النبأ", suraNameEg: "An-Naba", ayaNumber: "40"),
  SurahDataModel(index: 79, suraNameAr: "النازعات", suraNameEg: "An-Nazi'at", ayaNumber: "46"),
  SurahDataModel(index: 80, suraNameAr: "عبس", suraNameEg: "Abasa", ayaNumber: "42"),
  SurahDataModel(index: 81, suraNameAr: "التكوير", suraNameEg: "At-Takwir", ayaNumber: "29"),
  SurahDataModel(index: 82, suraNameAr: "الإنفطار", suraNameEg: "Al-Infitar", ayaNumber: "19"),
  SurahDataModel(index: 83, suraNameAr: "المطففين", suraNameEg: "Al-Mutaffifin", ayaNumber: "36"),
  SurahDataModel(index: 84, suraNameAr: "الإنشقاق", suraNameEg: "Al-Inshiqaq", ayaNumber: "25"),
  SurahDataModel(index: 85, suraNameAr: "البروج", suraNameEg: "Al-Buruj", ayaNumber: "22"),
  SurahDataModel(index: 86, suraNameAr: "الطارق", suraNameEg: "At-Tariq", ayaNumber: "17"),
  SurahDataModel(index: 87, suraNameAr: "الأعلى", suraNameEg: "Al-A'la", ayaNumber: "19"),
  SurahDataModel(index: 88, suraNameAr: "الغاشية", suraNameEg: "Al-Ghashiyah", ayaNumber: "26"),
  SurahDataModel(index: 89, suraNameAr: "الفجر", suraNameEg: "Al-Fajr", ayaNumber: "30"),
  SurahDataModel(index: 90, suraNameAr: "البلد", suraNameEg: "Al-Balad", ayaNumber: "20"),
  SurahDataModel(index: 91, suraNameAr: "الشمس", suraNameEg: "Ash-Shams", ayaNumber: "15"),
  SurahDataModel(index: 92, suraNameAr: "الليل", suraNameEg: "Al-Lail", ayaNumber: "21"),
  SurahDataModel(index: 93, suraNameAr: "الضحى", suraNameEg: "Adh-Dhuha", ayaNumber: "11"),
  SurahDataModel(index: 94, suraNameAr: "الشرح", suraNameEg: "Ash-Sharh", ayaNumber: "8"),
  SurahDataModel(index: 95, suraNameAr: "التين", suraNameEg: "At-Tin", ayaNumber: "8"),
  SurahDataModel(index: 96, suraNameAr: "العلق", suraNameEg: "Al-Alaq", ayaNumber: "19"),
  SurahDataModel(index: 97, suraNameAr: "القدر", suraNameEg: "Al-Qadr", ayaNumber: "5"),
  SurahDataModel(index: 98, suraNameAr: "البينة", suraNameEg: "Al-Bayyina", ayaNumber: "8"),
  SurahDataModel(index: 99, suraNameAr: "الزلزلة", suraNameEg: "Az-Zalzalah", ayaNumber: "8"),
  SurahDataModel(index: 100, suraNameAr: "العاديات", suraNameEg: "Al-Adiyat", ayaNumber: "11"),
  SurahDataModel(index: 101, suraNameAr: "القارعة", suraNameEg: "Al-Qari'ah", ayaNumber: "11"),
  SurahDataModel(index: 102, suraNameAr: "التكاثر", suraNameEg: "At-Takathur", ayaNumber: "8"),
  SurahDataModel(index: 103, suraNameAr: "العصر", suraNameEg: "Al-Asr", ayaNumber: "3"),
  SurahDataModel(index: 104, suraNameAr: "الهمزة", suraNameEg: "Al-Humazah", ayaNumber: "9"),
  SurahDataModel(index: 105, suraNameAr: "الفيل", suraNameEg: "Al-Fil", ayaNumber: "5"),
  SurahDataModel(index: 106, suraNameAr: "قريش", suraNameEg: "Quraish", ayaNumber: "4"),
  SurahDataModel(index: 107, suraNameAr: "الماعون", suraNameEg: "Al-Ma'un", ayaNumber: "7"),
  SurahDataModel(index: 108, suraNameAr: "الكافرون", suraNameEg: "Al-Kafirun", ayaNumber: "6"),
  SurahDataModel(index: 109, suraNameAr: "النصر", suraNameEg: "An-Nasr", ayaNumber: "3"),
  SurahDataModel(index: 110, suraNameAr: "المسد", suraNameEg: "Al-Masad", ayaNumber: "5"),
  SurahDataModel(index: 111, suraNameAr: "الإخلاص", suraNameEg: "Al-Ikhlas", ayaNumber: "4"),
  SurahDataModel(index: 112, suraNameAr: "الفلق", suraNameEg: "Al-Falaq", ayaNumber: "5"),
  SurahDataModel(index: 113, suraNameAr: "الناس", suraNameEg: "An-Nas", ayaNumber: "6")
];
